# Generated by Django 4.1 on 2026-06-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_eixotecnologia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
        migrations.AlterModelTable(
            name='eixotecnologia',
            table='eixo',
        ),
    ]
