# Generated by Django 5.2.15 on 2026-06-25 19:13

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_alter_autor_table_alter_eixotecnologia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', tinymce.models.HTMLField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('id_fk_autor', models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='associados.autor')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='associados.eixotecnologia')),
            ],
            options={
                'db_table': 'artigo',
            },
        ),
    ]
